version: '3.8'

services:
  # Nest.js service
  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=vijaysugali98
      - DB_NAME=pricetracker
    depends_on:
      - db

  # PostgreSQL Database service
  db:
    image: postgres:14
    container_name: nest-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vijaysugali98
      POSTGRES_DB: pricetracker
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Define a named volume for the database data
volumes:
  postgres-data:
